### PR TITLE
=== DO NOT MERGE ! TEST PR ===

### PR DESCRIPTION
**Pull request by michalxo**

### CODE REVIEW

**Comment by michalxo** [comment]
Random pbla

**Comment by rhmessagingqe** [comment]
Some Test Comment

**Comment by rvais** [comment]
Simple comment, test text transformed into lorem ipsum AI generated, hash-tag not really ...

**Comment by tlbueno** [comment]
just a test comment :-D

**Comment by rhmessagingqe** [comment]
Tiago look! Magic

**Comment by michalxo** [comment]
@rhmessagingqe claire smoke pr_init: 18 pr_kubernetes: 80 pr_operator: 720 pr_broker: 31

**Comment by rhmkrutov** [comment]
Commentating for sake of commenting

**Comment by michalxo** [comment]
@rhmessagingqe claire all pr_init: 13

**Pull request closed without merging**
